---
title: "Clustering"
output: html_notebook
---

#### Autor: Nga Vu

```{r}
library(tidyverse)
library(caret)
library(cluster)
```

```{r}
library(readr)
all <- read_csv("all.csv")
```
Data reinigen, auswählen und Dummy Data erstellen:

```{r}
user_book <- all %>% 
  group_by(`Book-Title`) %>% 
  mutate(count = n()) %>% 
  filter(count > 199) %>% 
  filter(`Book-Rating` > 9)%>% 
  select(`User-ID`, `Book-Title`) %>% 
  unique()

book_matrix <- user_book %>% 
  mutate(i=1) %>% 
  spread(`Book-Title`, i, fill = 0)
# Anmerkung:
# Soll die "User-ID" Spalte entfernt werden, weil die Werte bei User-ID ist keinen Merkmale zum clustern, sondern zum Identifizieren der User?
```

```{r}
rm(all)
```

### Versuchen Sie die Leser aus dem Buch-Datansatz zu clustern: Welche Bücher gehören in welches Cluster?

1 - Distanz heraufinden: 

```{r}
book.dist <- dist(book_matrix, method = "euclidean")
```

2 - K finden:

```{r}
wss <- (nrow(book_matrix)-1)*sum(apply(book_matrix,2,var))
  for (i in 2:10) wss[i] <- sum(kmeans(book_matrix,
                                       centers=i)$withinss)
plot(1:10, wss, type="b", xlab="Number of Clusters",
     ylab="Within groups sum of squares")
```

Wir nehmen k = 2, da ab 2 Clusters gibt es keine größe Unterschied der Varianz innerhalb eines Clusters

#### Hierachische Clustering:
```{r}
book.hc <- hclust(book.dist, method = "ward.D2")
plot(book.hc)
class <- cutree(book.hc, k = 2)
rect.hclust(book.hc, k=2, border = "blue")
```

```{r}
# In Tabelle zeigen, zu welchem Cluste gehört ein User
result1 <- book_matrix %>% 
  mutate(cluster = class) %>% 
  select(`User-ID`, cluster) %>% 
  left_join(user_book)
```

#### K-Means Clustering:

```{r}
k.means.fit <- kmeans(book_matrix, 2)
```

```{r}
clusplot(book_matrix, k.means.fit$cluster, color=TRUE, shade=TRUE,
labels=4, lines=0, main="K-means cluster plot")
```

```{r}
# Join user_book Tabelle, um zu wissen, welches Buch gehört zu welchem Cluster
result2 <- as.data.frame(cbind(book_matrix$`User-ID`,k.means.fit$cluster))
result2 <- result2 %>% 
  left_join(user_book, by= c("V1"="User-ID"))
  
```